### ISSUE TITLE
MVC 패턴 폴더 생성

### ISSUE THREAD

**Issue by daejun4582** [JustOneBite/job-backend#2]
**Description**
- MVC 패턴을 위한 폴더 생성 및 server.js 파일명 변경

**Todo**
- [x] models 폴더 생성
- [x] routes 폴더 생성
- [x] controllers 폴더 생성
- [x] server.js 파일 app.js로 파일명 변경

**ETC**
- details
